### ISSUE TITLE
多人开发的时候，用configure配置去中心化，如果两个人都命名了一个相同的module模块，会不会冲突出错

### ISSUE THREAD

**Issue by Running563** [concentjs/concent#11]
请教下，多人开发的时候，用configure配置去中心化，如果两个人都命名了一个相同的module模块名，会不会冲突出错？？

**Comment by fantasticsoul** [comment]
会报错
```
run api error: module xx duplicate
```
虽然支持去中心化配置，但是最终还是会合并到全局上下文的`RootState`、`RootReducer`、`RootComputed`这些对象上的，所以是不允许重复，需要开发者约定好命名规则。

**Comment by fantasticsoul** [comment]
已解决
