### ISSUE TITLE
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性

### ISSUE THREAD

**Issue by ccwq** [concentjs/concent#14]
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性
用了两周1个问题，在组件外，如何获取和修改状态如何监控获取计算属性

**Comment by fantasticsoul** [comment]
参考这个例子
https://codesandbox.io/s/concent-cu-4hetf?file=/src/index.js

```js
import { setState, getComputed } from 'concent';

setInterval(()=>{
  setState('login', {firstName:'out-'+Date.now()})
}, 2000);

setInterval(()=>{
  const cu = getComputed('login')
  console.log('cu.nickName: ', cu.nickName);
}, 2000);
```

想要主动感知计算属性变了，必需写在watch内部，getComputed仅用于获取计算结果
见此示例：https://codesandbox.io/s/concent-watch-7j0mw

```js
import React from "react";
import "./styles.css";
import { run, useConcent, defWatch } from 'concent';

run({
  login:{
    state:{
      //...
    },
    reducer:{
      //...
    },
    computed: {
      //...
    },
    watch:{
      // watchKey name和stateKey同名，默认监听name变化
      name(newState, oldState){
        console.log(`name changed from ${newState.name} to ${oldState.name}`);
      },
      // 从newState 读取了addr， info两个属性的值，当前watch函数的依赖是 addr, info
      // 它们任意一个发生变化时，都会触发此watch函数
      addrOrInfoChanged: defWatch((newState, oldState, fnCtx)=>{
        const {addr, info} = newState;
        if(fnCtx.isFirstCall)return;// 仅为了收集到依赖，不执行逻辑
        console.log(`addr is${addr}, info is${JSON.stringify(info)}`);
      }, {immediate:true})
    }
  }
})


```

**Comment by fantasticsoul** [comment]
组件外获取状态
```js
import { getState } from 'concent';

getState('login'); // 获得login模块的状态
```

**Comment by ccwq** [comment]
> 组件外获取状态
> 
> ```js
> import { getState } from 'concent';
> 
> getState('login'); // 获得login模块的状态
> ```

感谢解答，非常棒的框架。

**Comment by fantasticsoul** [comment]
好的，期待你能够探索到更多精彩有趣的特性并使用起来。
