### ISSUE TITLE
一些初次使用的反馈

### ISSUE THREAD

**Issue by roytan883** [concentjs/concent#18]
问题1：this.ctx.state和this.ctx.reducer语义的歧义

在使用this.ctx.state的时候，拿到的是本模块myModule的state，这个没问题很直观
但是同样的用this.ctx.reducer，拿到的却是全局的reducer，里面有
`{"$$default":xxx，"$$global": yyy，"myModule": zzz}`
this.ctx.reducer为什么不是自己模块的reducer？如果需要访问全局的，弄一个this.ctx.rootReducer不是更直观吗？

问题2：
通过dispatch传入字符串函数名的用法感觉很古老，不好用：
`this.ctx.dispatch('doLogin', { userName: xxx, password: yyy });`
连参数都还要手动再把名字写一次{name:xxx, password:yyy}），
最方便不应该是`this.ctx.reducer.doLogin(xxx, yyy)`这样吗？

问题3：
目前使用起来最痛苦的是对于模块（因为模块models代码在ui之外的其它目录，仅仅是run的时候注册进去的，ide无感），因为没法ide智能感知代码，state和reducer使用的时候全靠手动写。不像平时用this.state或者hooks里面，都可以直接感知到，敲代码很方便

**Comment by fantasticsoul** [comment]
你好，非常感谢使用concent，你的问题我帮你解答，希望能让你满意哈

1
`this.state`不完全代表所属模块的状态，代表的是所属模块状态和当前实例私有状态合并后的状态

```js
run({
    counter:{state:{ count: 1 }}
})

@register('counter')
class Demo extends React.Component{
  state = {show: false}
  render(){
      const state = this.state;
      // or
      // const state =this.ctx.state

      console.log(this.state);// {count:1, show:false}
      console.log(this.ctx.moduleState);// {count:1}
  }
}
```
经过上面示例你应该明白为什么有`moduleReducer`了吧，实际上对应的`moduleComputed`，`connectedState`,`connectReducer`属性，`moduleReducer`可以调用别名`mr`，`connectReducer`也支持别名`cr`

```
this.ctx.mr.doXXXX(payload)
this.ctx.cr.fooModule.doYYY(payload)
```

拿到的reducer是`rootReducer`是为了方便合concent里暴露的`reducer`对等
```
import { reducer } from 'concent';
// reducer 是一个根reducer，方便用户在一些特性地方使用
// 当然了，你再控制台`cc.reducer.***`也能够直接调用
```
问题2：
`dispatch`是为了动态调用接口，其实更推荐的是`this.ctx.mr.xxxMethod`或者`this.ctx.cr.xxModule.yyMethod`这样的方式呀

问题3：
和问题2差不多，只是暂时你不知道如果标注类型而已，事实上相比`mobx`concent彻底消灭了`this`， `reducer`,`computed`,`state`都只是普通的json对象或方法，对类型标注是及其友好的, 提供了`StateType`,`CompuetdValType`,`ReducerType`等辅助类型帮助用户导出真正的运行时类型，只需要用户集中导出并维护所有模块类型，则可以全局使用，所以`concent`推荐用户将类型写到`src/types/store.d.ts`(针对js项目)或者`src/types/store.ts`(针对ts项目)，然后就可以到处方便的使用类型了。

简单示例1，如何导出`cc.reducer`类型：
https://codesandbox.io/s/stupefied-ardinghelli-9t8rh?file=/src/pages/A.js

示例2，js-project
https://codesandbox.io/s/concent-guide-xvcej?file=/src/types/store.d.ts

示例3，ts-project
https://codesandbox.io/s/concent-guide-ts-zrxd5
欢迎clone git https://github.com/fantasticsoul/concent-guid-ts 试运行。

示例4，todo-mvc
https://codesandbox.io/s/todoapp-react-concent-fvgvc?file=/src/types/store.d.ts

**Comment by roytan883** [comment]
@fantasticsoul  

问题1了解了

问题2
> this.ctx.mr.doLogin(['xxx', 222])

这种用法之前看文档没看到，那么第二个问题就解决了


问题3，有这些示例看看来用就好多了，之前看官网的文档没找到，待会儿我去试一试改了以后在webstrom里面可不可以感应代码提示。

非常感谢你的解答，concent这个库出发点非常好，解决了redux和mobx中的许多痛点。特别是前几天被hooks里面的callback闭包问题搞得烦，总是一会儿新值一会儿旧值，思考成本太高了。

总体来说上手不错，只是感觉上手文档稍微有点乱，我都是看文档，加例子，然后再加上看代码才上手的。比如昨天用react-router-concent的时候，按照readme那样用总是连不上，原来需要在run.js使用run以后加一个configureRoute()才行，这个还是看错误提示然后看了react-router-concent的源码才解决的。

**Comment by roytan883** [comment]
@fantasticsoul  另外问一下，concent可以在react native和electron上使用吗？因为我目前用的react全家桶做的全平台

**Comment by fantasticsoul** [comment]
你好，由于目前还是我一个人维护文档，所以可能有些地方还没来得及考虑周到，近期会在官网文档里加一个FAQ集合，将大家普遍遇到的问题收集起来，方便查阅和回顾，同时api文档也还需要更新，让读者更容易理解。

理论上来说concent能不能搭配react，和react运行在哪里应该没有关系，因为react最终还是运行在webview里的，所以应该是可以运行在electron里的(甚至concent还可以和类react框架搭配比如preact), 欢迎你开个仓库搭配electron试一试并给我更多反馈。

Rn这一块我也还没有试过(还从没有写过rn😓),不过我觉得rn和react本身有很多的抽象层是一致的，感觉应该也可以吧，也欢迎你开个仓库简单测一下，帮助我获得rn开发的反馈。

**Comment by fantasticsoul** [comment]
close issue
