### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by komaedaXnagito** [concentjs/concent#20]
RangeError: Maximum call stack size exceeded
    at Object.set (make-ob-state.js:14)
    at Object.set (make-ob-state.js:14)
    at Object.set (make-ob-state.js:14)
    at Object.set (make-ob-state.js:14)
    at Object.set (make-ob-state.js:14)
    at Object.set (make-ob-state.js:14)
    at Object.set (make-ob-state.js:14)
    at Object.set (make-ob-state.js:14)
    at Object.set (make-ob-state.js:14)
    at Object.set (make-ob-state.js:14)

**Comment by komaedaXnagito** [comment]
示例代码，模拟用户输入带来的重新渲染，实际场景中存在需要用户填写大量数据的场景，用户反馈越填写页面越卡。实际上用户填写的内容并没有涉及到concent中相关的state或是effect等内容。使用示例代码可以发现页面刷新肉眼可见变慢，然后卡死抛出异常。去掉useConcent相关代码对比可以发现渲染没有变慢。concent版本2.4.0，2.4.4，2.4.18均可复现
const iState = () => ({ show: true, cool: 1, good: 2 });
function CcFnComp() {
  const { state, syncBool } = useConcent({
    module: "counter",
    state: iState
  });
  const [value,setValue] = React.useState([{v:0,id:0},{v:0,id:1}])
  const xxx = value[0].v;
  React.useEffect(()=>{
    setTimeout(()=>{
      const newValue = [...value];
      if(xxx.length>20){
        newValue[0].v = 'reset'
      }else{
          newValue[0].v = xxx+"0";
        }
          setValue(newValue);
    },10)
  },[xxx])
  return (
    <div>
      {xxx}
    </div>
  );
}

**Comment by fantasticsoul** [comment]
你好，请给出具体的实例代码，或者在[codesandbox](https://codesandbox.io)创建一个实例并发送链接在issue，方便我跟踪和定位问题，或者分析你的代码本身可能有问题。

你的第二个答复里这段代码完全看不出什么问题, 第一个答复里明显是由死循环了。

**Comment by komaedaXnagito** [comment]
https://codesandbox.io/s/determined-johnson-7htdt?file=/src/App.js

**Comment by komaedaXnagito** [comment]
> 你好，请给出具体的实例代码，或者在[codesandbox](https://codesandbox.io)创建一个实例并发送链接在issue，方便我跟踪和定位问题，或者分析你的代码本身可能有问题。
> 
> 你的第二个答复里这段代码完全看不出什么问题, 第一个答复里明显是由死循环了。

https://codesandbox.io/s/determined-johnson-7htdt?file=/src/App.js
循环只是为了模拟用户输入导致的重新渲染，改成input输入上百字符一样会出问题。

**Comment by fantasticsoul** [comment]
你这个问题和concent没关系啊，是你对`useEffect`的理解有问题，你的代码将`xxx`的值传入依赖列表，然后在回调里又改变了`xxx`的值，这和你在类组件的`componentIDidUpdate`里调用`this.setState`是一样的危险行为---> 触发UI无限重渲染，建议你多看看api手册了解下`useEffect`的执行时机。
```
  const [value, setValue] = React.useState([{ v: 0, id: 0 }, { v: 0, id: 1 }]);
  const xxx = value[0].v;
  React.useEffect(() => {
    console.log('React.useEffect22');
    setTimeout(() => {
      const newValue = [...value];
      if (xxx.length > 20) {
        newValue[0].v = "reset";
      } else {
        newValue[0].v = xxx + "0";
      }
      setValue(newValue);
    }, 10);
  }, [xxx]);
```

**Comment by fantasticsoul** [comment]
最后推荐如果使用了cocnent，可以用 `ctx.effect`替代原始的生命周期函数
