### ISSUE TITLE
React Native项目中报错

### ISSUE THREAD

**Issue by roytan883** [concentjs/concent#24]
尝试在RN中使用，但是加载编译就失败了
```
error: Error: Unable to resolve module `react-dom` from `node_modules\concent\src\core\base\append-dispatcher.js`: react-dom could not be found within the project.
```

**Comment by fantasticsoul** [comment]
升级到`2.5.1`即可，最新版本在内部去掉了`react-dom`依赖

**Comment by roytan883** [comment]
@fantasticsoul 

```
Can't find variable: localStorage

concent\src\cc-context\index.js 264:26
```

RN 官方建议使用
https://github.com/react-native-community/async-storage
这个库好像也支持web

**Comment by fantasticsoul** [comment]
> RN 官方建议使用
> https://github.com/react-native-community/async-storage
> 这个库好像也支持web

感谢推荐，升级至`2.5.2`即可，调整了`localStorage`的获取策略，在web环境默认是window.localStorage，在rn环境，你需要人工的在run的时候在`options`参数里传入第三方实现库
```js
import AsyncStorage from '@react-native-community/async-storage';
import { run } from 'concent';

run({
     /** your store config */
  },{
   localStorage: AsyncStorage,
})
```

**Comment by fantasticsoul** [comment]
你好，现在最新的情况如何了呢

**Comment by roytan883** [comment]
不好意思，今天在忙其它的，我明天来测试 2.5.2

**Comment by roytan883** [comment]
@fantasticsoul OK，已经可以正常使用了。没有全面测试，但是基本的`appCtx.setState`，`appCtx.moduleComputed.fullName2`, `appCtx.moduleReducer.changeFirstName`都是可以使用的

**Comment by fantasticsoul** [comment]
好的，感谢提供帮助，欢迎继续提供新的issue，有了你们 concent才会越来越好越来越强大
