### ISSUE TITLE
API设计的疑问

### ISSUE THREAD

**Issue by Qinmei** [concentjs/concent#26]
说实话，我不是很理解在API中加入computed跟watch这种；

我认为所有用户能够手动实现的功能，我们可以通过中间件去实现， 可以通过第三方库去实现， 而不应该由框架直接提供；

**Comment by fantasticsoul** [comment]
你好，框架做的事情就是尽量将复杂的细节收拢，提供最简单的api给用户使用，如果类似`redux`这样，其实到最后用户都不会去使用原生的`redux`的，而是`redux-toolkit`、`rematch`等。

可了解这篇文章：https://juejin.im/post/5e7c18d9e51d455c2343c7c4#heading-22

而且mobx也提供了类似的`computed`装饰器啊，岂不是也设计有问题了？

并且concent的computed非常强大的，仅仅是函数，但是有有两层依赖收集

1，computed定义时，自动收集对state的依赖
```
// code in models/counter/computed.js

// 这个doubleCount结算函数的依赖是 count 值，仅当count发生变化时，触发此函数
export function doubleCount({count}){
   return count * 2;
}

// 这个countSum计算函数依赖是 count,  countBig
export function countSum({count, countBig}){
  return count +  countBig
}
```

2 , 消费computed数据时，动态的依赖收集

```js
export const LoginFnSmall = React.memo(props => {
  const { state, moduleComputed: mcu, syncBool } = useConcent({
    module: "login",
    state: { show: true }
  });

  // 因为doubleCount是依赖count计算出来的，
  // 所以show为true时实例的依赖为count，仅当count发生变化时触发其渲染
  // 为false时，则无任何依赖
  return (
    <>
      <h1>Fn Small Comp</h1>
      <button onClick={syncBool("show")}>toggle</button>
      {state.show ? <div> fullName:{mcu.doubleCount}</div> : ""}
    </>
  );
});
```


而且`concent`也提供[插件](https://concentjs.github.io/concent-doc/guide/concept-plugin)机制和[中间件](https://concentjs.github.io/concent-doc/guide/concept-middleware)机制去扩展其他能力的。

目前已提供的插件有
[concent-plugin-redux-devtool](https://github.com/concentjs/concent-plugin-redux-devtool)

[concent-plugin-loading](https://github.com/concentjs/concent-plugin-loading)

[concent-plugin-async-computed-status](https://github.com/concentjs/concent-plugin-async-computed-status)

基于此，兼容redux插件生态也是很容易的事情呀

**Comment by fantasticsoul** [comment]
欢迎试用一下，computed核心功能，又框架提供才能保证完整的使用体验哦。

**Comment by Qinmei** [comment]
直接用官方的useMemo就能判断依赖有没有变化，副作用useEffect就能实现watch，框架提供这些API的意义何在？mobx这样设计不代表就是真理， 如果说连质疑的声音都不能有， 那我觉得也没啥好讨论的了

**Comment by fantasticsoul** [comment]
可以质疑，任何框架的api都有自己的考虑的，之所以将 `computed` 内置就是因为它能够化繁为简并能够提供更强大的功能。

useMemo需要手动维护依赖，`computed`是自动的，`computed`结果还具有运行时的依赖收集功能，`computed`还可以是[异步的](https://codesandbox.io/s/async-computed-35byz?file=/src/App.js:1378-2042)，这些都是`useMemo`不能提供的，且写法更简单，定义处负责计算数据，使用处负责取数

`watch`和`useEffect`的执行时机不一样的，`watch`是渲染前触发，`useEffect`是渲染完毕触发，但concent同样提供`ctx.effect`完全替代`useEffect`，从未避免每一次渲染都要书写`useEffect`且手动传递依赖的问题

可以查看这篇文章[深度解析useEffect 和 ctx.effect](https://juejin.im/post/5deb43256fb9a0166316c3e9)

最后的最后，这些api或者说特性都是可选的(computed, watch ,setup ,effect, event 等等)，当用户理解到了一定层次时自然会发现他们的妙处，不理解的话完全忽视即可。

完全遵从[最原始的react写法](https://codesandbox.io/s/rvc-demo2-vg3uh?file=/src/index.js)就可以了，对于任何新手几乎都没有负担，会用`react`即会用`concent`。

```
import { run, setState, getState } from "concent";

run({
  counter: {// 声明一个counter模块
    state: { num: 1 }, // 定义状态
  }
});

function FnComp() {
  const { state, setState } = useConcent("counter");
  const changeNum = () => setState({ num: 20 });
  
  return (
    <div>
      <h1>fn comp: {state.num}</h1>
      <button onClick={changeNum}>changeNum</button>
    </div>
  );
}

@register("counter")
class ClsComp extends React.Component {
  changeNum = () => this.setState({ num: 10 })
  render() {
    return (
      <div>
        <h1>class comp: {this.state.num}</h1>
        <button onClick={this.changeNum}>changeNum</button>
      </div>
    );
  }
}
```

如有兴趣，可以参考[特性一览](https://codesandbox.io/s/green-tdd-g2mcr)

**Comment by tingkai-zhang** [comment]
谢谢作者详细认真的解答，作为一个初学者，我决定用concent来改写一个我的项目。
