### ISSUE TITLE
在当前实例 如何 获取同模块其他实例的state 或 其他模块实例的state 数据呢？ 

### ISSUE THREAD

**Issue by liuxingpluck** [concentjs/concent#29]
在当前实例 如何 获取同模块其他实例的state 或 其他模块实例的state 数据呢？ 

举个例子：我有个 foo 模块，有 实例 foo1 foo2 foo3 ，和 bar 模块  有实例 bar1 bar2 bar3 
现在 在 foo1 实例 获取 foo2 foo3 和 bar1 bar2 的state 数据

**Comment by fantasticsoul** [comment]
如果是同一个模块的其他实例，大家的状态都是来自于同一个模块，它们是一样的呀，为什么要去获取其他实例的状态呢，获取模块的状态即可。

获取状态和实例是没关系的其实，所以我这里把你的问题稍稍调整一下，如果获取其他模块的状态？

*  仅获取，不产生订阅关系

```js
import { getState } from 'concent';

function Bar(){
   const fooState = getState('foo');
   const barState = getState('bar');
}
```
> 此种模式适合于组件外部某些方法拿状态

*  通过连接产生订阅关系

```js
import { useConcent } from 'concent';

function Bar(){
   // 当前组件连接到foo模块和bar模块
   const {connectedState} = useConcent({connect:['foo', 'bar']});
   const fooState = connectedState.foo;
   const barState = connectedState.bar;
}
```

查看更多关于`useConcent`
https://concentjs.github.io/concent-doc/api/g-use-concent

**Comment by liuxingpluck** [comment]
那我换个方式说咯：在 实际业务中，我们遇到这样一种情况，有一种 动态控件：SearchForm 用于查询，它的各种明细控件，都是从数据库 查询出来的，举例来说：

**Comment by fantasticsoul** [comment]
大概明白你的意思了，其实数据不是需要你主动找出实例去设置的，而是任意一个实例修改了store的数据后，框架帮忙自动同步到其他实例上

你这个例子的数据模型是，某个模块下state里有个list，list遍历后生成一个个组件，concent提供一个renderKey机制帮忙用户实现高效的渲染

针对你说的情况特意给你写了个在线示例（注意打开log查看，渲染了只改渲染的部分）
https://codesandbox.io/s/render-key-dwrx1?file=/src/Cell.js

关于更多renderKey可查看此文的rendKey章节
https://juejin.im/post/5da7cb9cf265da5bbb1e4f8c#heading-12

**Comment by liuxingpluck** [comment]
谢谢，看完你的 示例后,我已经基本确定 符合我的要求了，我实际中 最终的写法 是 使用 顶层api：
cc.reducer.某模块.函数(payload:{},{renderkey:‘xxx’}) 

因为 实际业务 中 有些 是其他模块的 按钮 去触发 这个数据的变化，你觉得有木有什么 更好的方法嘛？

**Comment by fantasticsoul** [comment]
其他模块的组件 不读取foo模块的状态，仅仅想调用它的方法的话，可以如这个示例一样
https://codesandbox.io/s/concent-guide-ts-zrxd5?file=/src/components/biz-smart/Menu.tsx
使用一个带类型的ccReducer去触发

如果是动态的调用则使用顶层api dispatch方式或者实例ctx 的 dispatch方式

```js
import { dispatch } from 'concent';

dispatch('foo/method', 'payload');

// 实例里可以 ctx.dispatch('foo/method', 'payload');
```

当然了其实dispatch支持调用函数的
```js
import { dispatch } from 'concent';
import { method } from 'models/foo/reducer';

dispatch(method, 'payload');// 直接导出foo模块的method的方法并调用
```

不过这种方式没有`ccReducer`方便😀

**Comment by fantasticsoul** [comment]
> 谢谢，看完你的 示例后,我已经基本确定 符合我的要求了，我实际中 最终的写法 是 使用 顶层api：
> cc.reducer.某模块.函数(payload:{},{renderkey:‘xxx’})
> 
> 因为 实际业务 中 有些 是其他模块的 按钮 去触发 这个数据的变化，你觉得有木有什么 更好的方法嘛？

已给你的这个实例添加了类型标记，你可以很方便的享受IDE智能提示语跳转了
https://codesandbox.io/s/render-key-dwrx1
