### ISSUE TITLE
反馈bug:模块一开始的 state 为 空对象，那么 函数组件中 获取到的 state 一直为空，不受 reducer 影响

### ISSUE THREAD

**Issue by liuxingpluck** [concentjs/concent#32]
示例如下：
我定义了一个 Product 模块 ，组件 默认 state 为 {}
==================================================
run({
"product": { state: {}, reducer: { ...prodcutReducer } }
})
==================================================
现在 我定义了 一个 class 组件 regeister(‘product’) Product
==================================================
该 组件 内部 有一个 函数组件：ApplyDDUser 
function ApplyDDUser(props) {
    const ctx = useConcent({module: "product", props}, 'ApplyDDUser');
    const { state, setState } = ctx;
    const { showApplyProductUser } = state;
   if(!showApplyProductUser )return null;
    ....

    return 渲染代码
}
==================================================
Product 有一个 componentDidMount 生命周期，调用 reducer：this.ctx.mr.getProuct(params || {});
从 服务器 异步获取 一个数据,会会 更新 状态 showApplyProductUser  为 true，
==================================================
但是 现在 ApplyDDUser 怎么 都拿不到 product 模块的state，一直为 空对象{}
==================================================
另外 ，我的代码平台是 基于 taro3的，最近在 做一个微信小程序，不知道 是否跟这些有关系？

**Comment by fantasticsoul** [comment]
你好，这是由于你对实例state和模块state的理解没有到位导致的使用错误

```js
// 函数组件
const { state, moduleState} = useConcent('foo');
// 类组件
const { state, moduleState} = this.ctx;// this.state === this.ctx.state
```

上述代码里`state`即实例state，`moduleState`即模块state，`state`是模块state和私有state的合成体，当你的模块foo没有申明任何状态时，某个属于foo模块的组件实例调用reducer返回的新状态只会影响到这个组件实例，并不会传递给其他实例

```js
@register('foo')
class Demo extends Component(){
  componentDidMount(){
    this.ctx.mr.callMethod(222);
  }
}

// in reducer.js
export function callMethod(payload){
  return {aNewKey: payload}
}
```

aNewKey是一个没有在模块里声明过的key名字，concent智能的会对reducer调用返回状态做了智能的分拣操作，筛出非模块状态的那一部分状态，并将这个返回状态传回调用reducer的实例（谁调用了就传递给谁），达到了和`setState`是一样的效果，因为`setState`可以动态的扩展实例状态里没有声明过key的。

分拣筛出的模块状态才会提交到store并分发给其他实例，所以对于concent来说无论是`setState`还是`reducer`调用，都不能扩展**模块状态**里的key的，这是规则限制，所以要共享的key，都必须提前在moduleState里声提前声明。

```js
@register('foo')
class Demo extends Component(){
  render(){
    const { state, moduleState} = this.ctx;
    // state: {aNewKey: 222}, 由刚才的callMethod调用赋值
    // moduleState {}，这里始终为空，因为模块状态本身就是空
  }
}
```

如果此时我们有另外一个组件也属于foo，他的state永远也读不到`aNewKey`，因为这个key是某个实例私有的

```js
function Demo2(){
  const { state, moduleState} = useConcent('foo');
    // state: {}, 
    // moduleState {}
}
```

所以你还理解下面几个点即可想明白问题原因所在了

- state是私有状态和模块状态的合成体
- 只有模块状态才能被共享到其他地方
- reducer返回(也可以是setState提交)的新状态，会被分拣为两部分，模块状态和非模块状态。

解决此问题也就很简单了，2个方法
- 父组件透传下去
- 把状态提前声明到模块里
