### ISSUE TITLE
文档中关于函数组件的注册问题

### ISSUE THREAD

**Issue by SterbenJ** [concentjs/concent#34]
## 文档中代码[倒数第四行](https://concentjs.github.io/concent-site/docs/doc-guid-quick-start#function%E7%BB%84%E4%BB%B6)

```
...
//## 连接模块，组装函数组件
const connectFn = connectDumb({state, setup, mapProps, module:'welcomeModule'});
...
```

执行时浏览器会报如下错误
```
react_devtools_backend.js:2273 Error: CcFragment or CcClass's prop connect is invalid, module[mapProps] not found in cc store
```

## 改成如下后正常运行
```
...
//## 连接模块，组装函数组件
const connectFn = registerDumb({state, setup, mapProps, module:'welcomeModule'});
...
```
[在线示例](https://stackblitz.com/edit/cc-course-hello-concent-complex)中使用的也是`registerDumb`方法

**Comment by fantasticsoul** [comment]
感谢提示，那里代码写错了，不过最新的文档地址是：
https://concentjs.github.io/concent-doc

你贴的那个已经不维护了，`connectDumb`只能传要连接的模块数组，是对`registerDumb`的浅封装，不支持传递其他参数，需要使用其他参数的话需要用`registerDumb`

```js
connectDumb(['a', 'b', 'c'])
// 其实是调用registerDumb
registerDumb({connect: ['a', 'b', 'c']})
```
