### ISSUE TITLE
renderKey在2.0版本中失效bug

### ISSUE THREAD

**Issue by maweimaweima** [concentjs/concent#35]
根据官方介绍高性能demo，在本地环境中使用concent 2.7.25，发现不更新列表元素的试图
在线上demo中，update最新包，修改书籍名称同样出现问题。
[访问地址](https://stackblitz.com/edit/concent-render-key-4ehnyu?file=package.json)

**Comment by fantasticsoul** [comment]
BookItem里的第八行
```js
const renderKey = ctx.ccUniqueKey;
// 修改为
const renderKey = ctx.renderKey;
```

即可正常运行，或者将

```js
ctx.dispatch('changeBookName', { id, name }, renderKey);
// 修改为
ctx.dispatch('changeBookName', { id, name }, id);
```

最新版本对renderKey做了一个优化，如果实例指定了id，则renderKey为`props.id`，否则为`ccUniqueKey`
方便一份数据多次遍历生成不同的ui这种场景时，可以更加语义化的去同步多份ui的数据，可参考这里示例

https://codesandbox.io/s/render-key-dwrx1

by the way, 你把示例页面链接发我一下，我去修改，那里应该还没来得及更正

**Comment by fantasticsoul** [comment]
> 根据官方介绍高性能demo，在本地环境中使用concent 2.7.25，发现不更新列表元素的试图
> 在线上demo中，update最新包，修改书籍名称同样出现问题。
> [访问地址](https://stackblitz.com/edit/concent-render-key-4ehnyu?file=package.json)

感谢提示，已找到源码链接做了修正 https://stackblitz.com/edit/concent-render-key?file=BookItem.js
