### ISSUE TITLE
支持next.js吗

### ISSUE THREAD

**Issue by zhangwei900808** [concentjs/concent#37]
支持next.js吗

**Comment by fantasticsoul** [comment]
支持的，示例仓库在这里
https://github.com/concentjs/ssr-demo-1

**Comment by fwh1990** [comment]
@fantasticsoul  SSR + 持久层应该如何更优雅地处理？

**Comment by fantasticsoul** [comment]
> @fantasticsoul SSR + 持久层应该如何更优雅地处理？

你指的是浏览器端操作了一堆状态在内存里，然后直接刷新整个浏览器，页面重新下发给浏览器端后的状态如何还原吗？需要加个持久化中间件，然后由它来做状态现场还原。

**Comment by fwh1990** [comment]
是指浏览器里本身持久化了一些数据，但是Server Side也用到这些数据，或者server端重新生成了这部分数据。再次下发时，与浏览器里持久层的数据必然冲突。

在通用库 redux-persist 中也有相应的讨论，不过issue都是open状态
