### ISSUE TITLE
concent是否支持数据持久化中间件

### ISSUE THREAD

**Issue by ba1q1** [concentjs/concent#40]
您好，请教一下，我尝试着让concent接入redux-persist方案，它的接入方式需要劫持全部的reducer，concent有暴露此API吗？亦或者concent有自己的持久化实现方案？

**Comment by fantasticsoul** [comment]
你好，可以配置中间件 https://concentjs.github.io/concent-doc/guide/concept-middleware

你可以在这里将状态持久化到 localStorage 或则其他存储地。

目前还没有做这样一个持久化中间件，不过我可以很快补上发布的。

**Comment by fantasticsoul** [comment]
codesandbox 给了个最简版的实现，你可以参考下（后续会发布一个专用的持久化中间件，不入侵业务代码的那种）

https://codesandbox.io/s/quirky-fire-di0u5?file=/src/App.js

**Comment by ba1q1** [comment]
> codesandbox 给了个最简版的实现，你可以参考下（后续会发布一个专用的持久化中间件，不入侵业务代码的那种）
> 
> https://codesandbox.io/s/quirky-fire-di0u5?file=/src/App.js

非常感谢🙏希望concent越做越好

**Comment by fantasticsoul** [comment]
> > codesandbox 给了个最简版的实现，你可以参考下（后续会发布一个专用的持久化中间件，不入侵业务代码的那种）
> > https://codesandbox.io/s/quirky-fire-di0u5?file=/src/App.js
> 
> 非常感谢🙏希望concent越做越好

感谢支持哈，演示链接看到效果了吗，修改后可以刷新浏览器还原状态哦

**Comment by ba1q1** [comment]
> > > codesandbox 给了个最简版的实现，你可以参考下（后续会发布一个专用的持久化中间件，不入侵业务代码的那种）
> > > https://codesandbox.io/s/quirky-fire-di0u5?file=/src/App.js
> > 
> > 
> > 非常感谢🙏希望concent越做越好
> 
> 感谢支持哈，演示链接看到效果了吗，修改后可以刷新浏览器还原状态哦

已看到，非常感谢🙏
