### ISSUE TITLE
Is there any typescript support?

### ISSUE THREAD

**Issue by zjhken** [concentjs/concent#42]
Hi, I cannot find any typescript related words in the documentation, is that mean there is no typescript support for this package ?

**Comment by fantasticsoul** [comment]
> Hi, I cannot find any typescript related words in the documentation, is that mean there is no typescript support for this package ?

Hi, concent 100% fully support ts, see this demo: https://codesandbox.io/s/concent-guide-ts-zrxd5, or this git: https://github.com/tnfe/concent-pro
