### ISSUE TITLE
Is React Dependency Needed? Is 17v support?

### ISSUE THREAD

**Issue by n0isy** [concentjs/concent#47]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
      
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR! react@"^17.0.2" from the root project
npm ERR!  
npm ERR! Could not resolve dependency:   
npm ERR! peer react@"^16.13.0" from concent@2.14.21  
npm ERR! node_modules/concent    
npm ERR! concent@"^2.13.6" from the root project

**Comment by fantasticsoul** [comment]
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> 
> npm ERR! Found: react@17.0.2
> npm ERR! node_modules/react
> npm ERR! react@"^17.0.2" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.13.0" from concent@2.14.21
> npm ERR! node_modules/concent
> npm ERR! concent@"^2.13.6" from the root project

could you please offer me a minimal git example to reproduce this error?

I try the latest version react on codesandbox, but it works well
see https://codesandbox.io/s/cra-template-concent-ts-2x347?file=/src/features/counter/Counter.tsx

**Comment by n0isy** [comment]
--force param is working. Minimal example:
npm init
npm i react@^17
npm i concent
-- give error


npm --ver
-- npm@7.10.0
node --version
-- v12.16.1

**Comment by fantasticsoul** [comment]
I have just try your code in my terminal
```js
npm init
npm i react@^17
npm i concent
```
but no error printed. my npm ver is npm@6.14.10

I guess it is caused by npm some new strategy? yours is higher than mine.
