### ISSUE TITLE
为何版本从2020就停止维护了？

### ISSUE THREAD

**Issue by zhangwei900808** [concentjs/concent#56]
这样让想使用这个框架的人有点不放心啊

**Comment by fantasticsoul** [comment]
一直有在维护啊，你看提交记录，最近一个月都有更新的

**Comment by zhangwei900808** [comment]
@fantasticsoul 那为什么版本到2020就截止了

**Comment by fantasticsoul** [comment]
> @fantasticsoul 那为什么版本到2020就截止了

版本到2020截止是什么意思呢？最新的一版[2.15.14]( https://www.npmjs.com/package/concent )上个月才发布的呀
![image](https://user-images.githubusercontent.com/7334950/129296667-e95dbd8f-011c-4552-87f0-7cc6f48f56dc.png)

**Comment by zhangwei900808** [comment]
![image](https://user-images.githubusercontent.com/4385154/130019966-acc8f2dd-7889-4c81-9833-d92a6020f9db.png)

@fantasticsoul

**Comment by fantasticsoul** [comment]
抱歉最近一段时间未发tag，已对2.15版本做了里程碑
![image](https://user-images.githubusercontent.com/7334950/130382124-b7a43287-55e5-4c61-8814-b7adac105aed.png)
