### ISSUE TITLE
Rebuild the project with Typescript.

### ISSUE THREAD

**Issue by wgxh-cli** [concentjs/concent#58]
I am a typescript user, but this library just uses JSDoc provide type safe.
So i open this issue.
I think rebuild is a good idea, it can not only help users who use TypeScript, but also make this project more convenient to maintain.
I will help you and find more people to help you (possible).

加油!

**Comment by fantasticsoul** [comment]
感谢你的建议，将来会考虑，但因整个代码基于ts重构代价比较大，现阶段以稳定为主，事实上react源码里内部基于 flow 来标记类型同时对外提供了一份完整的d.ts 类型声明来保证用户层面的类型安全，concent也是内部基于 jsdoc 来标记类型同时对外提供了一份完整的d.ts文件，同时也配套提供了一个完整的ts项目实例哦，https://github.com/tnfe/tntweb-admin
