### ISSUE TITLE
修改既修改私有状态也修改模块状态的问题

### ISSUE THREAD

**Issue by 303182519** [concentjs/concent#60]
## 文档
https://concentjs.github.io/concent-doc/api-much-used/setState#%E6%97%A2%E4%BF%AE%E6%94%B9%E7%A7%81%E6%9C%89%E7%8A%B6%E6%80%81%E4%B9%9F%E4%BF%AE%E6%94%B9%E6%A8%A1%E5%9D%97%E7%8A%B6%E6%80%81

## 
为什么我点击addNum同时修改了num，bigxxx私有的，私有的不变化的？
https://codesandbox.io/s/shared-counter-forked-7bh0l?file=/src/App.js

**Comment by fantasticsoul** [comment]
已解决，更新到 2.16.1即可，codesandbox 见：https://codesandbox.io/s/shared-counter-forked-xykpu
修复见： https://github.com/concentjs/concent/commit/8979a2f3daf0281796604fa0e0eacb77fad7cca5
