### ISSUE TITLE
更新到2.16.4之后出现了报错

### ISSUE THREAD

**Issue by Handpear** [concentjs/concent#64]
Uncaught TypeError: Cannot destructure property 'store' of 'cc_context_default' as it is undefined.
![image](https://user-images.githubusercontent.com/40299372/140019904-99b20005-11c7-48d5-b0cf-57ca329d7daf.png)

**Comment by fantasticsoul** [comment]
你好，可以截图看下你现在的 run 接口代码截图吗

**Comment by fantasticsoul** [comment]
你好，更新到 2.16.5即可，出现了一个循环引用导致的

**Comment by fantasticsoul** [comment]
最新 https://github.com/tnfe/tntweb-admin 也同步升级到最新版本
