### ISSUE TITLE
[交流] 新状态库，求拍砖

### ISSUE THREAD

**Issue by fwh1990** [concentjs/concent#66]
项目地址：https://github.com/foca-js/foca
在线体验: https://codesandbox.io/s/foca-demos-e8rh3
比第一代redux-model更好用了。去掉了请求库，更加纯粹。Typescript方面一如既往100%类型提示

**Comment by fantasticsoul** [comment]
威武霸气

**Comment by fantasticsoul** [comment]
这个 defineModel 也是 concent 准备在v3里弄的，对单个model导入使用很方便，就是不好推rootState类型了，还是需要某个地方人工调用下类似 getAllModels 的函数来推导出 rootState rootComputed rootReduder 的类型

**Comment by fwh1990** [comment]
建议做一个vscode插件，自动监听模型文件，然后生成.d.ts文件。参考 https://github.com/prisma/prisma 的做法。

**Comment by fantasticsoul** [comment]
尴尬突然发现已经提供了，看到一个用户的git使用了
https://github.com/kolf/huaneng-admin/blob/master/src/models/me.ts

**Comment by fantasticsoul** [comment]
有点殊途同归的感觉了😀

**Comment by fwh1990** [comment]
升级到v3后，建议测试用例再多一点，最好都能覆盖，这样加功能和修bug都不虚。目前测试覆盖率还是偏低（78%）
