### ISSUE TITLE
关于 state 和 moduleState 的疑问

### ISSUE THREAD

**Issue by Handpear** [concentjs/concent#67]
你好，我有一个定义在reducer中的接口返回函数 userLogin，在实例中调用

![image](https://user-images.githubusercontent.com/40299372/149953678-b689029b-6ef9-4855-a0e8-d5f6a554f416.png)
![image](https://user-images.githubusercontent.com/40299372/149953124-b91f854d-73d5-4562-a2b9-602c8d2e7a0a.png)

然后分别打印 state 和 moduleState，发现结果不一样，moduleState 会把我的传参合并至 模块状态中，请问他是符合预期的吗？
![image](https://user-images.githubusercontent.com/40299372/149954419-32d19bf6-6523-43ff-9675-bef08b393da9.png)

文档中有以下这段话：
【属于某模块的组件，整个模块state将会合并到实例state上，如果组件没有对state做额外的字段扩展的话，state和 moduleState是一样的，如果做了额外的字段扩展（相当于私有的属性，不会被共享出去），那么只能从实例state上取到这些额外的字段值。】

我是不是触发了【额外的字段扩展】，怎么理解【额外的字段扩展】呢？希望可以详细了解下 state 和 moduleState 的区别

**Comment by itmanyong** [comment]
代码不全不是很好判断，不过从你的描述可能会存在一下情况。
1.你的userLogin是定义在reducer中的，reducer函数的返回内容会融合到对应的module中去，这是reducer的默认能力。
2.上图中的state内容应该是你system模块的默认数据吧，调用userlogin之后返回的数据融合到了system模块中，所以会有上图中的moduleState的数据。
3.moduleState会自动同步到实例的state，但是上图明显没有同步，导致这个问题的原因可能是因为你的state在不应该解构的地方被提前解构出来引用，失去响应导致的。
4.关于“额外的字段扩展”，其实就是你的组件内部状态，例如你的组件state={a:111},模块state={b:222},那么你的useConcent解构出来的state最终会是{a:111,b:222}这个形式。但是a的值你是只能在当前组件实例中读取和使用，而b由于是全局模块的，其他地方也可以使用，简单地说moduleState=模块的数据，state是实例私有数据+连接的模块的数据融合过后的

**Comment by itmanyong** [comment]
额外啰嗦一句：不要在setup函数的直接内部作用域解构状态，例如：function setup(ctx){const {state,props}=ctx;};这是不可取的。但你可以在内部函数内部这样解构。例如：function setup(ctx){  return { testFunc(){const {state}=ctx;} }  };这是可行的

**Comment by Handpear** [comment]
> 额外啰嗦一句：不要在setup函数的直接内部作用域解构状态，例如：function setup(ctx){const {state,props}=ctx;};这是不可取的。但你可以在内部函数内部这样解构。例如：function setup(ctx){ return { testFunc(){const {state}=ctx;} } };这是可行的

感谢您的分析解答和关于 setup 的建议！我在代码中的其他地方并没有解构过 state，我不知道是否是其他的问题导致的，以下是可以复现的一份简单代码

https://github.com/Handpear/concent-state-test

**Comment by fantasticsoul** [comment]
> https://github.com/Handpear/concent-state-test

你的代码不对？还未提交吗

![image](https://user-images.githubusercontent.com/7334950/150459679-09ad3f9c-aae5-4c9f-956f-859e1bf03690.png)

**Comment by Handpear** [comment]
> > https://github.com/Handpear/concent-state-test
> 
> 你的代码不对？还未提交吗
> 
> ![image](https://user-images.githubusercontent.com/7334950/150459679-09ad3f9c-aae5-4c9f-956f-859e1bf03690.png)

奇怪，我自己打印出来的结果和你的不一致

![image](https://user-images.githubusercontent.com/40299372/150460672-5035607d-25d3-49d6-95f0-12d388de0513.png)

版本：
node v14.17.6
pnpm 6.27.1

**Comment by fantasticsoul** [comment]
你提交下最新的代码呗，不信你重新克隆现在这份代码试试

**Comment by Handpear** [comment]
> 你提交下最新的代码呗，不信你重新克隆现在这份代码试试

我在项目中添加了一个视频（时长1分06秒），演示了从 clone 到 console.log，我不知道是否是其他地方出了问题

**Comment by itmanyong** [comment]
这个问题确实存在，异步情况下moduleState的状态未即时同步到实例state。
1.可能设计如此moduleState的实例state同步工作是异步的。那么这样就是正常的。
2.可能是由于组件未直接使用token导致的懒同步？当组件加上对token的使用后截然不同，state和moduleState是完全一致的。
![22222](https://user-images.githubusercontent.com/53500371/150738583-4cf1cfa0-b792-42ae-8f00-55083e0febe0.gif)

**Comment by fantasticsoul** [comment]
sorry，发现你的代码提交的不对，和你的图示表示完全不一样，你的state仅这些定义
![image](https://user-images.githubusercontent.com/7334950/158003801-6e225b15-b5ff-4c5a-8893-4e2fa1162236.png)

和你的截图不一样，不过我明白你的意思了，我来解释下这个问题的原因吧， ctx.state 是实例状态，ctx.moduleState 是模块状态，**moduleState 是 state 的子集**，如果用户不主动在视图渲染时使用到moduleState里任何值，意味着当前视图对moduleState没有任何依赖，所以concent不会主动把moduleState 更新到 state里，如果主动使用了则是在组件触发渲染时（何时渲染的调度由react控制）才会把 moduleState 合并到 state上，而你的示例里调用方法，然后直接在then里面打印 state，此时state依然是旧的，只有组件重渲染时才是新的，所以如果你在函数或者回调里使用模块状态，建议总是取 moduleState，state仅组件重渲染那一刻才会是最新的。

**Comment by fantasticsoul** [comment]
> 这个问题确实存在，异步情况下moduleState的状态未即时同步到实例state。 1.可能设计如此moduleState的实例state同步工作是异步的。那么这样就是正常的。 2.可能是由于组件未直接使用token导致的懒同步？当组件加上对token的使用后截然不同，state和moduleState是完全一致的。 ![22222](https://user-images.githubusercontent.com/53500371/150738583-4cf1cfa0-b792-42ae-8f00-55083e0febe0.gif)

ctx.state 是实例状态，ctx.moduleState 是模块状态，moduleState 是 state 的子集，如果用户不主动在视图渲染时使用到moduleState里任何值，意味着当前视图对moduleState没有任何依赖，所以concent不会主动把moduleState 更新到 state里，如果主动使用了则是在组件触发渲染时（何时渲染的调度由react控制）才会把 moduleState 合并到 state上，示例里调用方法然后直接在then里面打印 state，此时state依然是旧的，只有组件重渲染时才是新的，所以如果你在函数或者回调里使用模块状态，建议总是取 moduleState，state仅组件重渲染那一刻才会是最新的。
