### ISSUE TITLE
实例的watch监听对undefined不生效

### ISSUE THREAD

**Issue by itmanyong** [concentjs/concent#68]
当实例的watch监听的实例状态值变为undefined时不会触发监听逻辑，如下图所示，当值变为undefined时无log内容
![image](https://user-images.githubusercontent.com/53500371/150248034-710be348-4720-4f42-84fd-c51299dda9ff.png)

**Comment by fantasticsoul** [comment]
undefined被认为是无效值，被丢弃了，可以使用null替代哈

**Comment by itmanyong** [comment]
明白了！不过感觉有点不符逻辑，无论是在程序还是开发者看来，undefined虽然无效，但值确实变了。

**Comment by fantasticsoul** [comment]
> 明白了！不过感觉有点不符逻辑，无论是在程序还是开发者看来，undefined虽然无效，但值确实变了。

2.17.5+ 之后允许用户设置 undefined了
