### ISSUE TITLE
关于 dispatch 的 callback 问题

### ISSUE THREAD

**Issue by Handpear** [concentjs/concent#70]
有以下代码和打印结果，每次执行 dispatch 会触发 userLogin，这是按照预期工作的，但好像并不是每次都会执行 callback 回调

![image](https://user-images.githubusercontent.com/40299372/151116121-fd09f328-9074-4738-b484-1d635ed8d04e.png)
![image](https://user-images.githubusercontent.com/40299372/151116468-7f0fb062-ddb0-4ce3-9ba0-1fedff120912.png)

![image](https://user-images.githubusercontent.com/40299372/151116326-e684c757-32bf-4dfe-8cca-19cb6b455d43.png)

**Comment by Handpear** [comment]
项目地址
https://github.com/Handpear/concent-state-test

**Comment by fantasticsoul** [comment]
> 项目地址 https://github.com/Handpear/concent-state-test
好的，最近几天我会看下

**Comment by fantasticsoul** [comment]
> 项目地址 https://github.com/Handpear/concent-state-test

callback问题已修复，更新到 2.17.3即可
