### ISSUE TITLE
无法与 Next 12.1.0 一起使用

### ISSUE THREAD

**Issue by Shunjun** [concentjs/concent#73]
版本:
"concent": "^2.17.5",
"next": "^12.1.0",

问题描述：
Next 开发模式下，启动可以不报错但是无法显示页面，刷新页面后控制台报 document is not defined

此 demo 可以复现该问题
https://codesandbox.io/s/angry-meitner-bhjl87

看了一下next 在 ssr 的时候拿到了 concent 挂载的 window 对象， 导致 next 内部判断 isBrowser 为 true

<img width="625" alt="lQLPDhtBG-hVOpHNAxbNBOKwnXPV2kX8DJwCO1kIVYBJAA_1250_790" src="https://user-images.githubusercontent.com/10445938/159162307-0b18ef53-6112-4574-ab33-ec6c30145a41.png">

<img width="371" alt="0921327D-6762-4F2E-851A-5439585E6467" src="https://user-images.githubusercontent.com/10445938/159162494-fd85dd0c-fae2-4be7-adb2-0d2ef51c1eb2.png">

**Comment by fantasticsoul** [comment]
收到，这段代码还记得是为了让next 9 能够正常工作才加的，https://github.com/concentjs/ssr-demo-1

想不到next又做了调整了 o(╥﹏╥)o，所以这里我应该不要挂载window才ok么

**Comment by Shunjun** [comment]
next 只让在 useEffect 里使用 window ,其他地方使用都会报错...

https://nextjs.org/docs/migrating/from-create-react-app#safely-accessing-web-apis

**Comment by fantasticsoul** [comment]
已发布2.17.6版本，移出了for ssr 那段代码，可以再试试

**Comment by fantasticsoul** [comment]
2.17.6 + 不再主动生成window空对象
