### ISSUE TITLE
连接的模块无法触发更新!!!

### ISSUE THREAD

**Issue by itmanyong** [concentjs/concent#74]
1.简易的复现demo：[https://codesandbox.io/s/kind-wind-pmfxr1?file=/src/App.js](https://codesandbox.io/s/kind-wind-pmfxr1?file=/src/App.js)

**Comment by fantasticsoul** [comment]
不要传整个connectedState进去，这是一个不变的对象
![image](https://user-images.githubusercontent.com/7334950/162399700-3b9b4c1e-43a0-4c27-bc61-4903c12557dc.png)

**Comment by itmanyong** [comment]
即使是直接使用ctx.connectedState也无法同步界面更新,仿佛没有订阅到一样
![image](https://user-images.githubusercontent.com/53500371/162720091-12b030a3-663d-49ed-a88b-66bf07038397.png)

**Comment by fantasticsoul** [comment]
有可能是2.17版本的引入的bug，你更新到2.18试试呢，可以看下面这个链接是ok的

https://codesandbox.io/s/amazing-borg-3bke1l?file=/src/index.js
