### ISSUE TITLE
支持react18并发模式

### ISSUE THREAD

**Issue by geekact** [concentjs/concent#76]

**Comment by fantasticsoul** [comment]
已适配18的最新并发模式，更新到2.18.2即可，见示例：

https://codesandbox.io/s/show-render-key-with-form-z3c15o?file=/src/index.tsx

**Comment by fantasticsoul** [comment]
收到，你可以建一个 codesandbox示例或者git 仓库来复现问题吗？因为比较忙可能不能回复及时，我针对你的示例去做调优可能更快些，感谢。

**Comment by fantasticsoul** [comment]
看了 useMutableSource，第三方状态需要接入这个api来避免 撕裂问题。
