### ISSUE TITLE
虽然小众 但初步用起来真香 类似vuex存储就行 而setup是惊喜分离了数据逻辑

### ISSUE THREAD

**Issue by czzonet** [concentjs/concent#78]

**Comment by czzonet** [comment]
有没有devtool而不用每次cc.getState()查看状态？

**Comment by fantasticsoul** [comment]
试试这个
https://github.com/concentjs/concent-plugin-redux-devtool

<img width="952" alt="image" src="https://user-images.githubusercontent.com/7334950/190205430-59ce6e58-07a5-4060-88bb-7e20ee93eeb2.png">

**Comment by czzonet** [comment]
好用 已经足够使用啦 💯

**Comment by fantasticsoul** [comment]
> 好用 已经足够使用啦 💯

推荐了解下
https://github.com/tnfe/hel

**Comment by czzonet** [comment]
> > 好用 已经足够使用啦 💯
> 
> 推荐了解下模块联考新方案 hel，这样你就可以写远程react组件啦 https://github.com/tnfe/hel

感谢指路 👍

**Comment by fantasticsoul** [comment]
更轻量的状态库 helux 来了， https://github.com/tnfe/hel/tree/main/packages/helux，也可以试试哦
