### ISSUE TITLE
[bug] v2.19.12: react Invalid hook call

### ISSUE THREAD

**Issue by czzonet** [concentjs/concent#82]
![Snipaste_2022-10-22_21-50-02](https://user-images.githubusercontent.com/16220009/197342717-2c3cc4ab-028f-485a-890f-995e60185a75.png)

**Comment by fantasticsoul** [comment]
你好可以提供一个最新可现问题的仓库示例么

**Comment by fantasticsoul** [comment]
或者提供一个类似的线上示例复现也可以
https://codesandbox.io/s/concent-guide-xvcej?file=/src/App.js

**Comment by czzonet** [comment]
> 或者提供一个类似的线上示例复现也可以 https://codesandbox.io/s/concent-guide-xvcej?file=/src/App.js

出现在pnpm升级concent的时候

估计删除node_modules重装就好了 

或者用yarn可能就不会有

![Snipaste_2022-11-02_09-15-01](https://user-images.githubusercontent.com/16220009/199372226-ff7930f2-4d3a-4a1e-8eae-14e2d804446d.png)
