### ISSUE TITLE
文档中看到一些参数顺序不对

### ISSUE THREAD

**Issue by flyinghail** [concentjs/concent#9]
从 `https://concentjs.github.io/concent-doc/guide/concept-module-watch`
```js
watch:{
  firstName(n, o)=> { 
    console.log(`firstName changed from ${n.firstName} to ${o.firstName}`);
  },
  fullName:{
    fn:(newState)=> {
      console.log(`any value of firstName or lastName changed will trigger this`);
    },
    depKeys: ['firstName', 'lastName'],
  },
}
```
这个例子的参数名和 `https://stackblitz.com/edit/hook-setup?file=CounterSetupComputedWatch.js` 里面测试来看：watch 函数的第一个参数是 new，第二个参数是 old

但是从
```typescript
type WatchFn = (
  oldVal:any,
  newVal:any, 
  fnCtx:FnCtx,
)=> void;
```
和
```js
console.log(`firstName changed from ${n.firstName} to ${o.firstName}`);
```
看，第一个是 old 第二个是 new....

---
`https://concentjs.github.io/concent-doc/api/g-register`
这个文档里面的例子，`register` 参数都是反的
```js
@register('Foo', {module:'foo', watchedKeys:['f1']})
class Foo extends Component{
  ...
}

import { register } from 'concent';
@register('Foo', {
  module:'foo', 
  watchedKeys:['f1'], 
  connect:{bar:'*'}}, //连接到bar模块，观察它的所有key值变化，
)
class Foo extends Component{
  ...
}
```

**Comment by fantasticsoul** [comment]
你好感谢提醒，已修正，文档还正在建设中，还请多多关注哈

**Comment by fantasticsoul** [comment]
已修正

**Comment by flyinghail** [comment]
`register` 中是改过了
不过 `https://concentjs.github.io/concent-doc/guide/concept-module-watch` 这个里面没有改动，是 `WatchFn(newState, oldState)` 还是 `WatchFn(oldState, newState)`?

**Comment by fantasticsoul** [comment]
是 `WatchFn(newState, oldState)`, 文档待会儿修复哈
